/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 0cd29971-4b3a-42af-b66c-f9299e5c0eea
-/

/-
We formally prove the coverage bound lemma.
The lemma states that if a function $f(w, \cdot)$ is $L$-Lipschitz and the probability that $C \in U(X)$ is at least $1-\alpha$, then the probability that the maximum distance $\Delta(X, C)$ is bounded by $L \cdot \text{diam}(U(X))$ is also at least $1-\alpha$.
We define $\Delta(X, C)(\omega) = \sup_{c' \in U(X(\omega))} d(f(w, C(\omega)), f(w, c'))$.
The proof relies on the Lipschitz property: $d(f(w, C), f(w, c')) \le L \cdot d(C, c') \le L \cdot \text{diam}(U(X))$.
This implies that the event $\{C \in U(X)\}$ is contained in the event $\{\Delta(X, C) \le L \cdot \text{diam}(U(X))\}$, and the result follows by monotonicity of the measure.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Checking definitions and Delta.
-/
open MeasureTheory ProbabilityTheory Metric ENNReal Set

#check LipschitzWith
#check ENNReal
#check NNReal
#check PseudoEMetricSpace
#check PseudoMetricSpace

noncomputable def Delta_test {Ω 𝓧 𝓒 𝓦 E : Type*} [PseudoEMetricSpace 𝓒] [PseudoEMetricSpace E]
  (w : 𝓦) (f : 𝓦 → 𝓒 → E) (U : 𝓧 → Set 𝓒) (X : Ω → 𝓧) (C : Ω → 𝓒) (ω : Ω) : ENNReal :=
  ⨆ c' ∈ U (X ω), edist (f w (C ω)) (f w c')

/-
Definition of Delta.
-/
open MeasureTheory ProbabilityTheory Metric ENNReal Set

noncomputable def Delta {Ω 𝓧 𝓒 𝓦 E : Type*} [PseudoEMetricSpace 𝓒] [PseudoEMetricSpace E]
  (w : 𝓦) (f : 𝓦 → 𝓒 → E) (U : 𝓧 → Set 𝓒) (X : Ω → 𝓧) (C : Ω → 𝓒) (ω : Ω) : ℝ≥0∞ :=
  ⨆ c' ∈ U (X ω), edist (f w (C ω)) (f w c')

/-
Minimal reproduction of volume usage.
-/
open MeasureTheory ProbabilityTheory Metric Set

variable {Ω : Type*} [MeasureSpace Ω]

theorem test_vol (s : Set Ω) : volume s = volume s := rfl

theorem test_ineq (s : Set Ω) (α : ENNReal) : volume s ≥ 1 - α ↔ volume s ≥ 1 - α := Iff.rfl

/-
Testing LipschitzWith in context.
-/
open MeasureTheory ProbabilityTheory Metric ENNReal Set

variable {Ω 𝓧 𝓒 𝓦 E : Type*}
variable [MeasureSpace Ω]
variable [PseudoEMetricSpace 𝓒] [PseudoEMetricSpace E]

theorem coverage_bound_test
  (w : 𝓦) (f : 𝓦 → 𝓒 → E) (L : NNReal)
  (hf : LipschitzWith L (f w)) : True := True.intro

/-
If $f(w, \cdot)$ is $L$-Lipschitz and $C \in U(X)$ with probability at least $1-\alpha$, then $\Delta(X, C) \le L \cdot \text{diam}(U(X))$ with probability at least $1-\alpha$, where $\Delta(X, C)$ is the maximum distance from $f(w, C)$ to $f(w, c')$ for $c' \in U(X)$.
-/
open MeasureTheory ProbabilityTheory Metric ENNReal Set

variable {Ω 𝓧 𝓒 𝓦 E : Type}
variable [MeasureSpace Ω]
variable [PseudoEMetricSpace 𝓒] [PseudoEMetricSpace E]

def GoodEvent (X : Ω → 𝓧) (C : Ω → 𝓒) (U : 𝓧 → Set 𝓒) : Set Ω :=
  {ω | C ω ∈ U (X ω)}

def BoundEvent (w : 𝓦) (f : 𝓦 → 𝓒 → E) (U : 𝓧 → Set 𝓒) (X : Ω → 𝓧) (C : Ω → 𝓒) (L : NNReal) : Set Ω :=
  {ω | Delta w f U X C ω ≤ (L : ENNReal) * EMetric.diam (U (X ω))}

theorem coverage_bound
  (X : Ω → 𝓧) (C : Ω → 𝓒) (U : 𝓧 → Set 𝓒)
  (w : 𝓦) (f : 𝓦 → 𝓒 → E) (L : NNReal)
  (hf : LipschitzWith L (f w))
  (α : ENNReal)
  (h_cov : volume (GoodEvent X C U) ≥ 1 - α) :
  volume (BoundEvent w f U X C L) ≥ 1 - α := by
  refine' h_cov.trans _;
  apply_rules [ MeasureTheory.measure_mono ];
  unfold GoodEvent BoundEvent; aesop;
  unfold Delta; aesop;
  refine' le_trans ( hf.edist_le_mul _ _ ) _;
  exact mul_le_mul_left' ( EMetric.edist_le_diam_of_mem a_1 i_1 ) _